import { writeFileSync, readFileSync, existsSync, mkdirSync, chmodSync } from "node:fs";
import path from "node:path";
import type { Ctx } from "./ctx";
import type { ChannelKind } from "./types";

export function launcherName(kind: ChannelKind): string {
  return kind === "next" ? "claude-next" : "claude";
}
export function launcherPath(ctx: Ctx, kind: ChannelKind): string {
  return path.join(ctx.localBin, launcherName(kind));
}

// NOTE on escaping: this is a JS template literal producing a bash script.
// `\${...}` and `$PREFIX` / `$@` stay LITERAL in the output (runtime shell vars);
// only `${ctx.*}` and `${binaryPath}` are interpolated by JS at generation time.
export function renderLauncher(ctx: Ctx, binaryPath: string): string {
  return [
    `#!${ctx.prefix}/bin/bash`,
    `# Generated by claude-channel (ccx) — pins this channel to a specific binary.`,
    `export CLAUDE_CODE_TMPDIR="\${CLAUDE_CODE_TMPDIR:-$PREFIX/tmp}"`,
    `export DISABLE_AUTOUPDATER=1`,
    `BUN_BINARY_PATH="${binaryPath}" exec "${ctx.bunTermux}" "$@"`,
    ``,
  ].join("\n");
}

export function writeLauncher(ctx: Ctx, kind: ChannelKind, binaryPath: string): void {
  mkdirSync(ctx.localBin, { recursive: true });
  const p = launcherPath(ctx, kind);
  writeFileSync(p, renderLauncher(ctx, binaryPath));
  chmodSync(p, 0o755);
}

export function readLauncherBinary(ctx: Ctx, kind: ChannelKind): string | null {
  const p = launcherPath(ctx, kind);
  if (!existsSync(p)) return null;
  const m = readFileSync(p, "utf8").match(/BUN_BINARY_PATH="([^"]+)"/);
  return m ? m[1] : null;
}
