import { writeFileSync, readFileSync, existsSync, mkdirSync, chmodSync, rmSync } from "node:fs";
import path from "node:path";
import type { Ctx } from "./ctx";
import type { ChannelKind } from "./types";
import { RESOLV_REDIRECT_PATH, RESOLV_CONTENT } from "./patch";

export function launcherName(kind: ChannelKind): string {
  return kind === "next" ? "claude-next" : "claude";
}
export function launcherPath(ctx: Ctx, kind: ChannelKind): string {
  return path.join(ctx.localBin, launcherName(kind));
}

// NOTE on escaping: this is a JS template literal producing a bash script.
// `\${...}` and `$PREFIX` / `$@` stay LITERAL in the output (runtime shell vars);
// only `${ctx.*}` and `${binaryPath}` are interpolated by JS at generation time.
export function renderLauncher(ctx: Ctx, binaryPath: string): string {
  // The binary is byte-patched to read its DNS resolver config from
  // RESOLV_REDIRECT_PATH instead of the absent /etc/resolv.conf (see patch.ts).
  // Provision that file (idempotent, self-healing if deleted) before launch, so
  // c-ares has nameservers for OAuth login + token refresh. printf-escape the
  // content's newlines for the generated bash.
  const resolvEsc = RESOLV_CONTENT.replace(/\\/g, "\\\\").replace(/\n/g, "\\n");
  return [
    `#!${ctx.prefix}/bin/bash`,
    `# Generated by claude-channel (ccx) — pins this channel to a specific binary.`,
    `export CLAUDE_CODE_TMPDIR="\${CLAUDE_CODE_TMPDIR:-$PREFIX/tmp}"`,
    `export DISABLE_AUTOUPDATER=1`,
    `[ -r ${RESOLV_REDIRECT_PATH} ] || printf '${resolvEsc}' > ${RESOLV_REDIRECT_PATH} 2>/dev/null || true`,
    `BUN_BINARY_PATH="${binaryPath}" exec "${ctx.bunTermux}" "$@"`,
    ``,
  ].join("\n");
}

export function writeLauncher(ctx: Ctx, kind: ChannelKind, binaryPath: string): void {
  mkdirSync(ctx.localBin, { recursive: true });
  const p = launcherPath(ctx, kind);
  // Replace any existing launcher OR symlink. Without this, writeFileSync on a path
  // that is a symlink (e.g. a pre-existing `claude -> claude-next`) writes THROUGH the
  // link and clobbers the target instead of creating a distinct regular file.
  rmSync(p, { force: true });
  writeFileSync(p, renderLauncher(ctx, binaryPath));
  chmodSync(p, 0o755);
}

export function readLauncherBinary(ctx: Ctx, kind: ChannelKind): string | null {
  const p = launcherPath(ctx, kind);
  if (!existsSync(p)) return null;
  const m = readFileSync(p, "utf8").match(/BUN_BINARY_PATH="([^"]+)"/);
  return m ? m[1] : null;
}
